"""files table

Revision ID: 2dc0c18ad935
Revises: 838111bb1685
Create Date: 2024-07-28 11:56:15.366828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc0c18ad935'
down_revision = '838111bb1685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('file_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_file_name'), ['file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_file_size'), ['file_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_upload_date'), ['upload_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_files_upload_date'))
        batch_op.drop_index(batch_op.f('ix_files_file_type'))
        batch_op.drop_index(batch_op.f('ix_files_file_size'))
        batch_op.drop_index(batch_op.f('ix_files_file_name'))

    op.drop_table('files')
    # ### end Alembic commands ###
